SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ESPRADB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ESPRADB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ESPRADB` DEFAULT CHARACTER SET utf8 ;
USE `ESPRADB` ;

-- -----------------------------------------------------
-- Table `ESPRADB`.`RATINGS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ESPRADB`.`RATINGS` (
  `RATING_ID` INT NOT NULL,
  `RATING_NAME` VARCHAR(45) NULL,
  PRIMARY KEY (`RATING_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ESPRADB`.`MOVIE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ESPRADB`.`MOVIE` (
  `MOVIE_ID` VARCHAR(45) NOT NULL,
  `MOVIE_TITLE` VARCHAR(45) NULL,
  `POSTER` VARCHAR(100) NULL,
  `YEAR` DATE NULL,
  `RATINGS_RATING_ID` INT NOT NULL,
  PRIMARY KEY (`MOVIE_ID`),
  INDEX `fk_MOVIE_RATINGS1_idx` (`RATINGS_RATING_ID` ASC) VISIBLE,
  CONSTRAINT `fk_MOVIE_RATINGS1`
    FOREIGN KEY (`RATINGS_RATING_ID`)
    REFERENCES `ESPRADB`.`RATINGS` (`RATING_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ESPRADB`.`MOVIE_GENRES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ESPRADB`.`MOVIE_GENRES` (
  `GENRE_ID` INT NOT NULL,
  `MOVIE_ID` VARCHAR(45) NOT NULL,
  INDEX `fk_MOVIE_GENRES_GENRE1_idx` (`GENRE_ID` ASC) VISIBLE,
  INDEX `fk_MOVIE_GENRES_MOVIE1_idx` (`MOVIE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_MOVIE_GENRES_GENRE1`
    FOREIGN KEY (`GENRE_ID`)
    REFERENCES `ESPRADB`.`GENRE` (`GENRE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MOVIE_GENRES_MOVIE1`
    FOREIGN KEY (`MOVIE_ID`)
    REFERENCES `ESPRADB`.`MOVIE` (`MOVIE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ESPRADB`.`GENRE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ESPRADB`.`GENRE` (
  `GENRE_ID` INT NOT NULL,
  `GENRE_NAME` VARCHAR(45) NULL,
  PRIMARY KEY (`GENRE_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ESPRADB`.`MOVIE_GENRES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ESPRADB`.`MOVIE_GENRES` (
  `GENRE_ID` INT NOT NULL,
  `MOVIE_ID` VARCHAR(45) NOT NULL,
  INDEX `fk_MOVIE_GENRES_GENRE1_idx` (`GENRE_ID` ASC) VISIBLE,
  INDEX `fk_MOVIE_GENRES_MOVIE1_idx` (`MOVIE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_MOVIE_GENRES_GENRE1`
    FOREIGN KEY (`GENRE_ID`)
    REFERENCES `ESPRADB`.`GENRE` (`GENRE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MOVIE_GENRES_MOVIE1`
    FOREIGN KEY (`MOVIE_ID`)
    REFERENCES `ESPRADB`.`MOVIE` (`MOVIE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ESPRADB`.`PERSON`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ESPRADB`.`PERSON` (
  `PERSON_ID` VARCHAR(45) NOT NULL,
  `IMAGE` VARCHAR(100) NULL,
  `FNAME` VARCHAR(45) NULL,
  `LNAME` VARCHAR(45) NULL,
  `DOB` DATE NULL,
  PRIMARY KEY (`PERSON_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ESPRADB`.`ACTOR_DETAILS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ESPRADB`.`ACTOR_DETAILS` (
  `ACTOR_ID` VARCHAR(45) NOT NULL,
  `PERSON_ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ACTOR_ID`),
  INDEX `fk_ACTOR_DETAILS_PERSON1_idx` (`PERSON_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ACTOR_DETAILS_PERSON1`
    FOREIGN KEY (`PERSON_ID`)
    REFERENCES `ESPRADB`.`PERSON` (`PERSON_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ESPRADB`.`CAST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ESPRADB`.`CAST` (
  `MOVIE_ID` VARCHAR(45) NOT NULL,
  `ACTOR_ID` VARCHAR(45) NOT NULL,
  INDEX `fk_CAST_MOVIE1_idx` (`MOVIE_ID` ASC) VISIBLE,
  INDEX `fk_CAST_ACTOR_DETAILS1_idx` (`ACTOR_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CAST_MOVIE1`
    FOREIGN KEY (`MOVIE_ID`)
    REFERENCES `ESPRADB`.`MOVIE` (`MOVIE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CAST_ACTOR_DETAILS1`
    FOREIGN KEY (`ACTOR_ID`)
    REFERENCES `ESPRADB`.`ACTOR_DETAILS` (`ACTOR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ESPRADB`.`DIRECTOR_DETAILS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ESPRADB`.`DIRECTOR_DETAILS` (
  `DIRECTOR_ID` VARCHAR(45) NOT NULL,
  `PERSON_ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DIRECTOR_ID`),
  INDEX `fk_DIRECTOR_DETAILS_PERSON1_idx` (`PERSON_ID` ASC) VISIBLE,
  CONSTRAINT `fk_DIRECTOR_DETAILS_PERSON1`
    FOREIGN KEY (`PERSON_ID`)
    REFERENCES `ESPRADB`.`PERSON` (`PERSON_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ESPRADB`.`DIRECTORS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ESPRADB`.`DIRECTORS` (
  `MOVIE_ID` VARCHAR(45) NOT NULL,
  `DIRECTOR_ID` VARCHAR(45) NOT NULL,
  INDEX `fk_DIRECTORS_MOVIE1_idx` (`MOVIE_ID` ASC) VISIBLE,
  INDEX `fk_DIRECTORS_DIRECTOR_DETAILS1_idx` (`DIRECTOR_ID` ASC) VISIBLE,
  CONSTRAINT `fk_DIRECTORS_MOVIE1`
    FOREIGN KEY (`MOVIE_ID`)
    REFERENCES `ESPRADB`.`MOVIE` (`MOVIE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DIRECTORS_DIRECTOR_DETAILS1`
    FOREIGN KEY (`DIRECTOR_ID`)
    REFERENCES `ESPRADB`.`DIRECTOR_DETAILS` (`DIRECTOR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ESPRADB`.`PRODUCER_DETAILS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ESPRADB`.`PRODUCER_DETAILS` (
  `PRODUCER_ID` VARCHAR(45) NOT NULL,
  `PERSON_ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PRODUCER_ID`),
  INDEX `fk_PRODUCER_DETAILS_PERSON1_idx` (`PERSON_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCER_DETAILS_PERSON1`
    FOREIGN KEY (`PERSON_ID`)
    REFERENCES `ESPRADB`.`PERSON` (`PERSON_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ESPRADB`.`PRODUCERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ESPRADB`.`PRODUCERS` (
  `MOVIE_ID` VARCHAR(45) NOT NULL,
  `PRODUCER_ID` VARCHAR(45) NOT NULL,
  INDEX `fk_PRODUCERS_MOVIE1_idx` (`MOVIE_ID` ASC) VISIBLE,
  INDEX `fk_PRODUCERS_PRODUCER_DETAILS1_idx` (`PRODUCER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCERS_MOVIE1`
    FOREIGN KEY (`MOVIE_ID`)
    REFERENCES `ESPRADB`.`MOVIE` (`MOVIE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCERS_PRODUCER_DETAILS1`
    FOREIGN KEY (`PRODUCER_ID`)
    REFERENCES `ESPRADB`.`PRODUCER_DETAILS` (`PRODUCER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ESPRADB`.`WRITER_DETAILS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ESPRADB`.`WRITER_DETAILS` (
  `WRITER_ID` VARCHAR(45) NOT NULL,
  `PERSON_ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`WRITER_ID`),
  INDEX `fk_WRITER_DETAILS_PERSON1_idx` (`PERSON_ID` ASC) VISIBLE,
  CONSTRAINT `fk_WRITER_DETAILS_PERSON1`
    FOREIGN KEY (`PERSON_ID`)
    REFERENCES `ESPRADB`.`PERSON` (`PERSON_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ESPRADB`.`WRITERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ESPRADB`.`WRITERS` (
  `MOVIE_ID` VARCHAR(45) NOT NULL,
  `WRITER_ID` VARCHAR(45) NOT NULL,
  INDEX `fk_WRITERS_MOVIE1_idx` (`MOVIE_ID` ASC) VISIBLE,
  INDEX `fk_WRITERS_WRITER_DETAILS1_idx` (`WRITER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_WRITERS_MOVIE1`
    FOREIGN KEY (`MOVIE_ID`)
    REFERENCES `ESPRADB`.`MOVIE` (`MOVIE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WRITERS_WRITER_DETAILS1`
    FOREIGN KEY (`WRITER_ID`)
    REFERENCES `ESPRADB`.`WRITER_DETAILS` (`WRITER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
